# Generated by Django 2.2.1 on 2019-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dates',
            field=models.TextField(default='[]'),
        ),
    ]
