# Generated by Django 2.2.2 on 2019-06-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_phase',
            new_name='project',
        ),
    ]
