# Generated by Django 2.2 on 2019-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepoint',
            name='approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
