# Generated by Django 2.2 on 2019-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepoint',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
