# Generated by Django 2.2 on 2019-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190508_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datepoint',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
