# Generated by Django 2.2.1 on 2019-06-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_ongoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='first_datepoint',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='last_datepoint',
        ),
    ]
