# Generated by Django 2.2.2 on 2019-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190614_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
