# Generated by Django 2.2 on 2019-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190517_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepoint',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
