# Generated by Django 2.2.2 on 2019-06-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectphase_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
