# Generated by Django 2.0 on 2019-06-07 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_datepoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ManyToManyField(related_name='client_project_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
