# Generated by Django 2.2.2 on 2019-06-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectphase_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphase',
            old_name='end',
            new_name='ongoing',
        ),
    ]
