# Generated by Django 2.2.2 on 2019-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190614_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
