# Generated by Django 2.0 on 2019-06-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datepoint',
            old_name='approved',
            new_name='approved_manager',
        ),
    ]
