# Generated by Django 2.0 on 2019-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190607_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepoint',
            name='approved_client',
            field=models.BooleanField(default=False),
        ),
    ]
