# Generated by Django 2.2.2 on 2019-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190614_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='first_month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='first_year',
            field=models.PositiveIntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='last_month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='last_year',
            field=models.PositiveIntegerField(default=2019),
        ),
    ]
