# Generated by Django 2.2.2 on 2019-06-14 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190614_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='first_month',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='first_year',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='last_month',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='last_year',
        ),
        migrations.AddField(
            model_name='projectphase',
            name='first_datepoint',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectphase',
            name='last_datepoint',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
