# Generated by Django 2.2.1 on 2019-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_datepoint_approved_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepoint',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
