# Generated by Django 2.2.2 on 2019-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190614_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='first_datepoint',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='last_datepoint',
            field=models.DateField(auto_now=True),
        ),
    ]
