# Generated by Django 2.2.1 on 2019-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_datepoint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepoint',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
