# Generated by Django 2.0 on 2019-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190614_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='dates',
            field=models.TextField(default='[]'),
        ),
    ]
