# Generated by Django 2.2.1 on 2019-06-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190610_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_per_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
