# Generated by Django 2.2.2 on 2019-06-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190613_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientDetails',
            new_name='ClientDetail',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='client_details',
            new_name='client_detail',
        ),
    ]
